server:
  port: 901
  
eureka:  instance:    hostname: eureka01.com  client:
    register-with-eureka: false #false表示不向注册中心注册本服务    fetch-registry: false #false表示此服务就是注册中心，用于维护服务实例，而不需要去检索服务    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机 设置Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka02.com:902/eureka/, http://eureka03.com:903/eureka/